### ISSUE TITLE
How can I access the comments?

### ISSUE THREAD

**Issue by acharkq** [aistairc/Numeracy-600K#1]
How can I get the full text of the comments from a piece of code like:

```json
{"id": 0, "UNIQUE_STORY_INDEX": "20160816085706nL3N1AX2ZW", "offset": 52, "length": 3, "magnitude": 1}
```

**Comment by ChunJiChen** [comment]
Please write us an email with the agreement. Email Address: cjchen@nlg.csie.ntu.edu.tw
