### ISSUE TITLE
could you please share all the dataset

### ISSUE THREAD

**Issue by RuiXilin0530** [aistairc/Numeracy-600K#2]
Hi, could you please share the specific market comments dataset? I couldn't find the content of market comments in the dataset.

**Comment by ChunJiChen** [comment]
Please write us an email with the agreement. Email Address: cjchen@nlg.csie.ntu.edu.tw
[Numeracy-600K_Agreement.pdf](https://github.com/aistairc/Numeracy-600K/files/3934652/Numeracy-600K_Agreement.pdf)
